### Lab 2
##### Task 1
- Scenario: You are processing player statistics for a sports analytics application.
1. Create a NumPy array for player statistics (heights, weights, points scored).
2. Update the weight of the player with the maximum points scored.
3. Append a new player's statistics to the array.
4. Insert a new statistic at a specified index within the array.
5. Delete the player with the lowest points scored.

In [ ]:
import numpy as np
stats = np.random.randint(1, 100, (100, 3))
# np.append()
stats

In [35]:
import numpy as np

player_stats = np.array([
    [180, 75, 30],
    [190, 85, 25],
    [175, 70, 40],
    [185, 90, 20]
])
player_stats


array([[180,  75,  30],
       [190,  85,  25],
       [175,  70,  40],
       [185,  90,  20]])

In [36]:
max_index = np.argmax(player_stats[:, 2])

# Update
player_stats[max_index, 1] = np.random.randint(100)
player_stats, max_index

(array([[180,  75,  30],
        [190,  85,  25],
        [175,  13,  40],
        [185,  90,  20]]),
 np.int64(2))

In [37]:
# New player
new_player = np.array([[178, 80, 35]])

# Append
player_stats = np.vstack([player_stats, new_player])
player_stats

array([[180,  75,  30],
       [190,  85,  25],
       [175,  13,  40],
       [185,  90,  20],
       [178,  80,  35]])

In [38]:
# Insert a new row at index 3
new_stat = [182, 78, 22]
player_stats = np.insert(player_stats, 3, new_stat, axis=0)
player_stats

array([[180,  75,  30],
       [190,  85,  25],
       [175,  13,  40],
       [182,  78,  22],
       [185,  90,  20],
       [178,  80,  35]])

In [39]:
# lowest points
min_index = np.argmin(player_stats[:, 2])

# Delete
player_stats = np.delete(player_stats, min_index, axis=0)
player_stats, min_index

(array([[180,  75,  30],
        [190,  85,  25],
        [175,  13,  40],
        [182,  78,  22],
        [178,  80,  35]]),
 np.int64(4))

#### Task 2
- Scenario: You are analyzing customer purchases.
1. Create two NumPy arrays for purchase amounts and item counts.
2. Create a shallow copy of one and a deep copy of the other.
3. Concatenate both arrays.
4. Split the concatenated array based on a condition.
5. Modify the original arrays and analyze the effects on the copies.

In [41]:
purchase_amounts = np.array([150, 200, 50, 75, 100])
item_counts = np.array([3, 5, 2, 4, 1])
purchase_amounts, item_counts

(array([150, 200,  50,  75, 100]), array([3, 5, 2, 4, 1]))

In [42]:
purchase_shallow = purchase_amounts.view()
item_counts_deep = item_counts.copy()
purchase_shallow, item_counts_deep, purchase_amounts, item_counts

(array([150, 200,  50,  75, 100]),
 array([3, 5, 2, 4, 1]),
 array([150, 200,  50,  75, 100]),
 array([3, 5, 2, 4, 1]))

In [43]:
combined_data = np.concatenate((purchase_amounts, item_counts))
combined_data

array([150, 200,  50,  75, 100,   3,   5,   2,   4,   1])

In [45]:
below_100 = combined_data[combined_data < 100]
above_or_equal_100 = combined_data[combined_data >= 100]
below_100, above_or_equal_100

(array([50, 75,  3,  5,  2,  4,  1]), array([150, 200, 100]))

In [46]:
print("Original purchase_amounts before change:", purchase_amounts)
print("Shallow copy:", purchase_shallow)
purchase_amounts[0] = 180
item_counts[1] = 6
print("Original purchase_amounts after change:", purchase_amounts)
print("Shallow copy:", purchase_shallow)
print("Original item_counts:", item_counts)
print("Deep copy:", item_counts_deep)


Original purchase_amounts before change: [150 200  50  75 100]
Shallow copy: [150 200  50  75 100]
Original purchase_amounts after change: [180 200  50  75 100]
Shallow copy: [180 200  50  75 100]
Original item_counts: [3 6 2 4 1]
Deep copy: [3 5 2 4 1]
